#!/bin/bash

str=""

# audio
if hash ponymix 2>/dev/null; then
    str+="$(ponymix get-volume)"
    if ponymix is-muted; then
        str+="M"
    fi
    str+=" |"
fi

# battery
if hash acpi 2>/dev/null; then
    output=$(acpi 2>&1)
    bat="$(echo "$output" | cut -d, -f2)"
    case $output in
        *Charging*)
            str+="$bat+ | "
            ;;
        *Discharging*)
            str+="$bat- | "
            ;;
        *Full*)
            str+="$bat | "
            ;;
        *"No support"*)
            str+=" "
            ;;
        *)
            str+="? | "
            ;;
    esac
fi

# date
str+="$( date +"%F %R" )"

/usr/bin/xsetroot -name "$str"
