#!/usr/bin/ruby

# Script to process events send by pianobar (pandora player).
# Referenced from .config/pianobar/config
# See pianobar's manpage section EVENTCMD

#start pianobar with pianobar | tee .config/pianobar/out
#figure out how to start in background (nohup? disown?)
#read .config/pianobar/out for status

case ARGV[0]    #event type
when 'userlogin'
    `echo "naughty.notify({text = 'pianobar started'}" | awesome-client`
when 'songstart'
    data = {}
    STDIN.each_line do |line|   # recieve data from pianobar on STDIN
        data.store(*line.chomp.split('=',2))     # store name=val in dict
    end
    artist = data['artist']
    song = data['title']
    IO.popen('awesome-client', 'w') do |pipe|
        pipe.puts("piano_update('#{artist}', '#{song}')")
        pipe.close_write
    end
end
