set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle
call vundle#rc()
" let vundle managle vundle - required!
Bundle 'gmarik/vundle'

" Bundles
" Run :BundleInstall after adding
" Run :BundleUpdate to update
" Run :BundleClean after removing
" vim-scripts
Bundle 'Tabmerge'
Bundle 'javacomplete'
Bundle 'vim-scripts/clips.vim'
" other repos
Bundle 'flazz/vim-colorschemes'
Bundle 'kien/ctrlp.vim'
Bundle 'Valloric/YouCompleteMe'
Bundle 'bling/vim-airline'
Bundle 'godlygeek/tabular'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-eunuch'
Bundle 'tpope/vim-fugitive'
Bundle 'Matt-Stevens/vim-systemd-syntax'
Bundle 'LaTeX-Box-Team/LaTeX-Box'
Bundle 'SirVer/ultisnips'
" End of Bundles
" YCM
let g:ycm_confirm_extra_conf = 0
let g:ycm_collect_identifiers_from_tags_files = 1

filetype plugin indent on
syntax on

" vim-latex settings
set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'

set rnu	            " Relative numbering
set nu	            " full line number on current line
set smartindent
set wildmenu        " Command line completion

set hlsearch        " highlight search results
set incsearch 	    " jump to result during search input
set ignorecase      " case insensitive searching

set showmatch	      " show matching brackets

set noerrorbells    " no annoying noise on error

set expandtab	      " tabs = spaces
set smarttab
set tabstop=2	      " 4 space tabs
set shiftwidth=2
set tw=80 	        " wrap text at 80 chars
let mapleader = "," "use , as leader character

set t_Co=256        "enable 256 colors
set t_AB=[48;5;%dm
set t_AF=[38;5;%dm
set bg=dark
colorscheme solarized

" vim-airline config
set laststatus=2    "always show
"let g:airline_left_sep='>'
"let g:airline_right_sep='<'
let g:airline_detect_modified=1
let g:airline_detect_paste=1
let g:airline_detect_iminsert=0
let g:airline_theme='solarized'
let g:airline_powerline_fonts=1
set guifont="Inconsolata for Powerline"

"Ultisnips config
let g:UltiSnipsSnippetsDir = "~/dotfiles/vim/UltiSnips"
let g:UltiSnipsEditSplit = "horizontal"
let g:UltiSnipsExpandTrigger = "<c-j>"
let g:UltiSnipsJumpForwardTrigger = "<c-j>"
let g:UltiSnipsJumpBackwardTrigger = "<c-k>"
let g:UltiSnipsListSnippets = "<c-i>"
"let g:UltiSnipsSnippetsDirectories = '~/dotfiles/vim/UltiSnips'

" vim-latex
let g:LatexBox_Folding=1
"CLIPS
au BufRead,BufNewFile *.clp set filetype=clips
"consular
au BufRead,BufNewFile ~/dotfiles/consular/termfiles/* set filetype=ruby
"javacomplete
autocmd Filetype java setlocal omnifunc=javacomplete#Complete
