set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle
call vundle#begin()
" let vundle managle vundle - required!
Bundle 'gmarik/vundle'

" Bundles
" Run :BundleInstall after adding
" Run :BundleUpdate to update
" Run :BundleClean after removing
Bundle 'altercation/vim-colors-solarized'
Bundle 'kien/ctrlp.vim'
Bundle 'Valloric/YouCompleteMe'
Bundle 'bling/vim-airline'
Bundle 'godlygeek/tabular'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-eunuch'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-dispatch'
Bundle 'Matt-Stevens/vim-systemd-syntax'
Bundle 'LaTeX-Box-Team/LaTeX-Box'
Bundle 'SirVer/ultisnips'
Bundle 'majutsushi/tagbar'
Bundle 'elzr/vim-json'
Bundle 'idanarye/vim-dutyl'
Bundle 'file:///home/erethar/project/nimrod.vim'
" End of Bundles
call vundle#end()
filetype plugin indent on
syntax on

" set mapleader here so it applies to all future keymaps
let mapleader = "," " use , as leader character

" remaining configuration settings are in plugin/**/*.vim
