#!/bin/bash

# From arch forums - process mailto's with mutt
# USAGE:
#
#    rename this script to XXX-newterminal to start new terminal window
#    with cmd=XXX and args=as passed (e.g., XXX=mutt)
#    when cmd completes, terminal window will close.

#GEOMETRY="-geometry 120x40"
TERMINAL="terminator"

CMD=$(basename "$0")
CMD="${CMD%*-newterminal}"
exec $TERMINAL $GEOMETRY -e "$CMD" "$@"
